#!/usr/bin/env bash


# ==============
# === Finder ===
# ==============

# show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true

# Display full POSIX path as window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Allow text selection in QuickLook
defaults write com.apple.finder QLEnableTextSelection -bool true


# ===================
# === Screenshots ===
# ===================

# Change Screenshots location
defaults write com.apple.screencapture location ~/Screenshots


# ================
# === Keyboard ===
# ================

# Disable long-press diacritics prompt in favor of key repeat
defaults write -g ApplePressAndHoldEnabled -bool false

# ===============
# === Windows ===
# ===============

# cmd+ctrl drag to drag from anywhere in a window
defaults write -g NSWindowShouldDragOnGesture -bool true

# play nicer with AeroSpace
defaults write com.apple.dock expose-group-apps -bool true
defaults write com.apple.spaces spans-displays -bool true


# ============
# === Misc ===
# ============

# Stop printing "Last login ..." line in new shells
touch ~/.hushlogin


# ====================================
# Finally, reload the changed defaults
killall SystemUIServer
