#!/usr/bin/env bash


# ==============
# === Finder ===
# ==============

# show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true

# Display full POSIX path as window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Allow text selection in QuickLook
defaults write com.apple.finder QLEnableTextSelection -bool true


# ===================
# === Screenshots ===
# ===================

# Change Screenshots location
defaults write com.apple.screencapture location ~/Screenshots


# ================
# === Keyboard ===
# ================

# Disable long-press diacritics prompt in favor of key repeat
defaults write -g ApplePressAndHoldEnabled -bool false



# ====================================
# Finally, reload the changed defaults
killall SystemUIServer
