#!/usr/bin/env bash


# ==============
# === Finder ===
# ==============

# show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true

# Display full POSIX path as window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Allow text selection in QuickLook
defaults write com.apple.finder QLEnableTextSelection -bool true


# ===================
# === Screenshots ===
# ===================

# Change Screenshots location
defaults write com.apple.screencapture location ~/Screenshots


# Finally, reload the changed defaults
killall SystemUIServer
